# Версия конфигурации, не менять!
version: 2.2

######################
# StopBotsJoin - 2.2 #
# Author: MrBrikster #
######################

# Прокси-сервер (BUNGEE или LILYPAD).
proxy: BUNGEE

# Сервер, на который игрок отправляется после прохождения проверки.
server: lobby

# Сообщение, которое отправляется в чат каждые 3 секунды.
message: '&f[&6Защита&f] &fПройдите паркур, чтобы попасть на сервер!'

# Мир, в котором находится паркур-защита.
world: world

# Включить ли ограничение по времени на прохождение паркура?
enablekick: false

# Максимальное количество ошибок. -1 для бесконечности.
maxerrors: -1

# Включить проверку PPS?
checkpps: true

# Максимальное значение PPS у игрока
maxpps: 35

# Включить режим отладки?
debug: true